name: maya_test_app
description: "A Send Money Flutter application."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_bloc: ^8.1.6
  equatable: ^2.0.5
  http: ^1.2.2
  shared_preferences: ^2.5.3
  intl: ^0.19.0
  get_it: ^8.0.3
  injectable: ^2.5.0
  json_annotation: ^4.9.0
  dio: ^5.8.0+1
  retrofit: ^4.4.1
  uuid: ^4.3.3
  lottie: ^3.3.1

dev_dependencies:
  build_runner: ^2.5.4
  copy_with_extension_gen: ^6.0.1
  fake_async: ^1.3.2
  flutter_gen_runner: ^5.10.0
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  injectable_generator: ^2.7.0
  json_serializable: ^6.9.5
  mockito: ^5.4.6
  retrofit_generator: ^9.2.0

flutter:
  uses-material-design: true

  assets:
    - .env/
    - assets/lottie/
